name: PlatformIO CI PSK
permissions:
  contents: write
  discussions: write
  actions: read
  checks: write
  pull-requests: write
  
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: master # Specify your branch name here
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Check PlatformIO
        run: pio system info

      - name: PWD
        run: |
          pwd
          ls -a

      - name: Build PlatformIO Project
        run: pio run

      - name: Upload PlatformIO Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: platformio-build
          path: .pio/build/**  # Adjust this path if necessary

#      - name: Upload multiple artifacts
#        uses: actions/upload-artifact@v4
#        with:
#          name: artifact1
#          path: path/to/artifact1
  
#      - name: Upload another artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: artifact2
#          path: path/to/artifact2

      - name: Create Release
        uses: softprops/action-gh-release@v2
        # only run this step when a tag is pushed with the format vX.X.X
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          #Remove this when the code acutally works
          prerelease: true
          generate_release_notes: true
          files: |
            .pio/build/**/*-merged.bin